# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c6d4d436f9b8dbb465d8ad861b549f11025d4fa9912cacbed3354f7361232cd848cbf3a099475194b9bbf4a8b02fd02f7185bfb56ed3a55f6024b9c60cfc84

test:
  secret_key_base: 42091fde573b401a20c1534d9bb187926ff9ab9efbd7b64b927199cc98c45b761a51056718667ae5ff1f725510bfeac100e8b5361c7937877a87996320aaa79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
